nodeLinker: node-modules
enableImmutableInstalls: false
enableGlobalCache: false

packageExtensions:
  "react-photo-gallery@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@chakra-ui/utils@*":
    peerDependencies:
      "react": "*"
