services:
  db:
    image: postgres:13
    container_name: aiartbase-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pirate228
      - POSTGRES_DB=Ai_ArtBase
    volumes:
      - ./backend/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app-network

  backend:
    # image: pavelshpagin/aiartbase-backend:latest
    build:
      context: ./backend
    container_name: aiartbase-backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:pirate228@db:5432/Ai_ArtBase
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - CHROMA_DB_PATH=/app/chroma_data
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - R2_ACCESS_KEY_ID=${R2_ACCESS_KEY_ID}
      - R2_SECRET_ACCESS_KEY=${R2_SECRET_ACCESS_KEY}
      - R2_ENDPOINT_URL=${R2_ENDPOINT_URL}
      - R2_BUCKET_NAME=${R2_BUCKET_NAME}
      - R2_PUBLIC_URL=${R2_PUBLIC_URL}
      - API_URL=${API_URL}
      - OWNER_ID=${OWNER_ID}
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
      - GCP_SA_TYPE=${GCP_SA_TYPE}
      - GCP_SA_PROJECT_ID=${GCP_SA_PROJECT_ID}
      - GCP_SA_PRIVATE_KEY_ID=${GCP_SA_PRIVATE_KEY_ID}
      - GCP_SA_PRIVATE_KEY=${GCP_SA_PRIVATE_KEY}
      - GCP_SA_CLIENT_EMAIL=${GCP_SA_CLIENT_EMAIL}
      - GCP_SA_CLIENT_ID=${GCP_SA_CLIENT_ID}
      - GCP_SA_AUTH_URI=${GCP_SA_AUTH_URI}
      - GCP_SA_TOKEN_URI=${GCP_SA_TOKEN_URI}
      - GCP_SA_AUTH_PROVIDER_URL=${GCP_SA_AUTH_PROVIDER_URL}
      - GCP_SA_CLIENT_CERT_URL=${GCP_SA_CLIENT_CERT_URL}
      - GCP_SA_UNIVERSE_DOMAIN=${GCP_SA_UNIVERSE_DOMAIN}
      - GCP_LOCATION=${GCP_LOCATION}

    depends_on:
      - db
      - chromadb
    restart: unless-stopped
    networks:
      - app-network

  chromadb:
    image: chromadb/chroma:0.6.3
    container_name: chromadb
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma
    ports:
      - "8001:8000"
    volumes:
      - ./backend/chroma_data:/chroma/chroma
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
# volumes:
#    postgres_data:
