"""Add num_likes column to arts table

Revision ID: 139f4003233c
Revises: 67fa75ed7d9a
Create Date: 2025-03-29 16:15:09.473008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '139f4003233c'
down_revision: Union[str, None] = '67fa75ed7d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('arts', sa.Column('num_likes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arts', 'num_likes')
    # ### end Alembic commands ###
