"""update database

Revision ID: 1d255ad12374
Revises: 1e663786a301
Create Date: 2025-05-05 13:50:20.220663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1d255ad12374'
down_revision: Union[str, None] = '1e663786a301'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_generated_arts_art_id', table_name='generated_arts')
    op.drop_index('ix_generated_arts_user_id', table_name='generated_arts')
    op.drop_table('generated_arts')
    op.add_column('arts', sa.Column('is_generated', sa.Boolean(), nullable=True))
    op.add_column('arts', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('arts', 'is_public')
    op.drop_column('arts', 'is_generated')
    op.create_table('generated_arts',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('art_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['art_id'], ['arts.id'], name='generated_arts_art_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='generated_arts_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'art_id', name='generated_arts_pkey')
    )
    op.create_index('ix_generated_arts_user_id', 'generated_arts', ['user_id'], unique=False)
    op.create_index('ix_generated_arts_art_id', 'generated_arts', ['art_id'], unique=False)
    # ### end Alembic commands ###
