"""Add generated_arts table and potentially fix indexes

Revision ID: 1e663786a301
Revises: d62b74ec737d
Create Date: 2025-05-03 08:39:49.999485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e663786a301'
down_revision: Union[str, None] = 'd62b74ec737d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
