"""Add likes column to Arts

Revision ID: 9fc6587699b4
Revises: cf2cbb8a1c28
Create Date: 2025-03-29 16:04:15.661828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc6587699b4'
down_revision: Union[str, None] = 'cf2cbb8a1c28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('arts', 'likes')
    # ### end Alembic commands ###
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('arts', sa.Column('likes', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
    pass
