"""Add generated_arts table

Revision ID: d62b74ec737d
Revises: ba0eb816ef37
Create Date: 2025-05-03 08:30:42.272365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd62b74ec737d'
down_revision: Union[str, None] = 'ba0eb816ef37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_art_owner_id', table_name='arts')
    op.drop_index('idx_like_user_art', table_name='likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_like_user_art', 'likes', ['user_id', 'art_id'], unique=False)
    op.create_index('idx_art_owner_id', 'arts', ['owner_id'], unique=False)
    # ### end Alembic commands ###
