name: Deploy to Production

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: pavelshpagin
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: pavelshpagin/aiartbase-backend:latest
          # Only pass non-sensitive build args
          build-args: |
            NODE_ENV=production

      - name: Build and push Scraper
        uses: docker/build-push-action@v2
        with:
          context: ./scraper
          push: true
          tags: pavelshpagin/aiartbase-scraper:latest
          # Only pass non-sensitive build args
          build-args: |
            NODE_ENV=production

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /root/aiartbase

            # Clean up disk space if needed
            docker system prune -af

            # Pull latest images
            docker pull pavelshpagin/aiartbase-backend:latest
            docker pull pavelshpagin/aiartbase-scraper:latest

            # Store environment variables from GitHub secrets
            cat > .env << EOF
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            ALGORITHM=${{ secrets.ALGORITHM }}
            ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
            CHROMA_DB_PATH=${{ secrets.CHROMA_DB_PATH }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }}
            R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}
            R2_ENDPOINT_URL=${{ secrets.R2_ENDPOINT_URL }}
            R2_BUCKET_NAME=${{ secrets.R2_BUCKET_NAME }}
            R2_PUBLIC_URL=${{ secrets.R2_PUBLIC_URL }}
            API_URL=${{ secrets.API_URL }}
            OWNER_ID=${{ secrets.OWNER_ID }}
            EOF

            # Deploy with Docker Compose
            docker compose down
            docker compose up -d

            # Show running containers
            docker compose ps

            # Display logs from services
            echo "Backend logs:"
            docker compose logs --tail 20 backend

            echo "Database logs:"
            docker compose logs --tail 20 db
