name: Deploy to Production

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: pavelshpagin
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Backend
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: pavelshpagin/aiartbase-backend:latest
          build-args: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            SECRET_KEY=${{ secrets.SECRET_KEY }}
            ALGORITHM=${{ secrets.ALGORITHM }}
            ACCESS_TOKEN_EXPIRE_MINUTES=${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}
            CHROMA_DB_PATH=${{ secrets.CHROMA_DB_PATH }}
            OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            R2_ACCESS_KEY_ID=${{ secrets.R2_ACCESS_KEY_ID }}
            R2_SECRET_ACCESS_KEY=${{ secrets.R2_SECRET_ACCESS_KEY }}
            R2_ENDPOINT_URL=${{ secrets.R2_ENDPOINT_URL }}
            R2_BUCKET_NAME=${{ secrets.R2_BUCKET_NAME }}
            R2_PUBLIC_URL=${{ secrets.R2_PUBLIC_URL }}
            API_URL=${{ secrets.API_URL }}
            OWNER_ID=${{ secrets.OWNER_ID }}

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/aiartbase
            export DATABASE_URL="${{ secrets.DATABASE_URL }}"
            export SECRET_KEY="${{ secrets.SECRET_KEY }}"
            export ALGORITHM="${{ secrets.ALGORITHM }}"
            export ACCESS_TOKEN_EXPIRE_MINUTES="${{ secrets.ACCESS_TOKEN_EXPIRE_MINUTES }}"
            export CHROMA_DB_PATH="${{ secrets.CHROMA_DB_PATH }}"
            export OPENAI_API_KEY="${{ secrets.OPENAI_API_KEY }}"
            export GEMINI_API_KEY="${{ secrets.GEMINI_API_KEY }}"
            export R2_ACCESS_KEY_ID="${{ secrets.R2_ACCESS_KEY_ID }}"
            export R2_SECRET_ACCESS_KEY="${{ secrets.R2_SECRET_ACCESS_KEY }}"
            export R2_ENDPOINT_URL="${{ secrets.R2_ENDPOINT_URL }}"
            export R2_BUCKET_NAME="${{ secrets.R2_BUCKET_NAME }}"
            export R2_PUBLIC_URL="${{ secrets.R2_PUBLIC_URL }}"
            export API_URL="${{ secrets.API_URL }}"
            export OWNER_ID="${{ secrets.OWNER_ID }}"
            docker stack deploy -c docker-stack.yml aiartbase
